version: '3'

services:
  mysql:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=admin
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./init/mysql/:/docker-entrypoint-initdb.d/:ro
    networks:
      - my_network

  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
    volumes: 
      - ./init/postgresql/:/docker-entrypoint-initdb.d/:ro
    networks:
      - my_network

  api-contatos:
    build: .
    depends_on:
      - mysql
      - postgresql
    ports:
      - "5000:5000"
    networks:
      - my_network

networks: 
  my_network:
    driver: bridge